Add interop matrix
flatcar/Flatcar pull request #390
Opened 2021-04-30 11:03 UTC by t-lo

# [Title: describe the change in one sentence]

Add initial version of the Flatcar interop matrix.

## How to use

See https://github.com/kinvolk/Flatcar/blob/t-lo/add-interop/interop-matrix.md.

2021-04-30 15:36 UTC, vbatts requested changes
on the whole good, though making it very visually obvious is the big thing.

2021-04-30 15:36 UTC, vbatts commented on interop-matrix.md
> +Support levels:
"support" level is confusing. And does not visually convey what we're wanting here.
This mnemonic needs to go away entirely.

Instead, just have columns, so folks can visually deduce the same. Like:

| Environment | Full-Feature (release blocker) | Works | Tested | Owner | Reference (e.g. GH issue) | Notes |
|-|:-:|:-:|:-:|-|-|-|
| EC2 | | X | X | @kinvolk/flatcar-maintainers | #107 | ... |
| Azure | | X | X | @kinvolk/flatcar-maintainers |  | ... |
| GCE | X | X | X | @kinvolk/flatcar-maintainers |  |  |
| Digital Ocean (VMs) | X | X | X | @kinvolk/flatcar-maintainers |  |  |
| Equinix Metal | X | X | X | @kinvolk/flatcar-maintainers |  |  |
| ESXi / vSphere | X | X | X | @kinvolk/flatcar-maintainers |  |  |
| Hetzner Cloud | | | X | [no owner] |  |  |
| Vultr VPS  | | | X | [no owner] |  |  |

2021-05-03 15:58 UTC, t-lo commented
Updated the PR based on the feedback provided by @vbatts .

2021-05-03 16:33 UTC, vbatts approved these changes
This is a good start. As folks will have links to their effort or tests, they can go here.

2021-05-04 08:17 UTC, merged