Sponsors: Add Flatcar sponsors to readme.
flatcar/Flatcar pull request #49
Opened 2020-03-20 10:52 UTC by t-lo

2020-03-20 11:01 UTC, invidian requested changes

2020-03-20 11:01 UTC, invidian commented on README.md
> +## Development Sponsorr
```suggestion
## Development Sponsors
```

2020-03-20 11:05 UTC, t-lo commented on README.md
> +## Development Sponsorr
Nice catch, thanks!

2020-03-23 17:27 UTC, t-lo commented
Addressed @invidian 's feedback.
Please note that the Github Diff document preview breaks image URLs; please use my PR branch directly for previewing the resulting README: https://github.com/flatcar-linux/Flatcar/tree/t-lo/add-sponsors

2020-03-23 18:01 UTC, invidian approved these changes
OK

2020-03-25 10:49 UTC, joaquimrocha reviewed
Left a comment about how the sponsors are organized.
Not setting as requesting changes because it's not something that's wrong in the pure definition of it nor my decision.

2020-03-25 10:49 UTC, joaquimrocha commented on README.md
> +[Giant Swarm](https://www.giantswarm.io/)
Maybe adding the sponsors in a table is better, as it allows the list to scale better without expanding the README vertically too much.
Also, should we just have links directly from the images? Sounds a bit redundant to have the labels with the names when the logos and titles already have that.

2020-05-05 11:18 UTC, merged