creating a maintainers file
flatcar/Flatcar pull request #842
Opened 2022-09-01 17:49 UTC by miao0miao

This file contains references to other repositories, they will include references to this file.

2022-09-02 06:10 UTC, t-lo requested changes
Can re rename `maintainers` -> `Maintainers.md` please?

2022-09-02 08:00 UTC, sayanchowdhury commented
> Can re rename `maintainers` -> `Maintainers.md` please?

Could it be MAINTAINERS.md or MAINTAINERS? Following the convention of README.md

2022-09-05 10:29 UTC, tormath1 commented on MAINTAINERS.md
> +* Krzesimir Nowak @Krzesimir Nowak @krnowak
Any reason to have duplicated name?
```suggestion
* Krzesimir Nowak @krnowak
```

2022-09-05 10:29 UTC, tormath1 commented on MAINTAINERS.md
> +Kai Lüke @pothos
For consistency: 
```suggestion
* Kai Lüke @pothos
```

2022-09-05 10:29 UTC, tormath1 commented on MAINTAINERS.md
> +* wrl
```suggestion
* @wrl
```

2022-09-05 10:29 UTC, tormath1 commented on MAINTAINERS.md
> +* Krzesimir Nowak @Krzesimir Nowak @krnowak
ditto.

2022-09-05 10:29 UTC, tormath1 commented on MAINTAINERS.md
> +* init
I don't think there is yet a primary maintainer for this? Maybe @pothos ?

2022-09-06 09:08 UTC, t-lo commented on MAINTAINERS.md
> +* Kai Lüke @pothos
```suggestion
* Kai Lüke @pothos 
* Gabriel Samfira @gabriel-samfira
```

2022-09-15 13:13 UTC, t-lo approved these changes
LGTM, thanks!

2022-09-15 13:14 UTC, merged